feature/CU-8678qnmk1: testing tj-actions/changed-files@v38

diff --git a/.github/workflows/prepare-changelog-for-update.yml b/.github/workflows/prepare-changelog-for-update.yml
--- a/.github/workflows/prepare-changelog-for-update.yml
+++ b/.github/workflows/prepare-changelog-for-update.yml
@@ -24,13 +24,21 @@ jobs:
         uses: actions/checkout@v3
         with:
           token: ${{ secrets.OWNER_PAT }}
+          fetch-depth: 0
 
-      - name: Check if CHANGELOG.md has been changed
+      - name: Get changed files
+        id: changed-files
+        uses: tj-actions/changed-files@v38
+        
+      - name: List all changed files
         run: |
-          if [[ $(git diff HEAD HEAD~1 --no-patch --exit-code CHANGELOG.md) ]]; then
-            echo "ERROR: Only CHANGELOG.md was modified. This is not allowed."
-            exit 1
-          fi
+          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            if [[ "$file" == "CHANGELOG.md" ]]; then
+              echo "ERROR: CHANGELOG.md was modified. This is not allowed."
+              exit 1
+            fi
+          done
+          
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
